[project]
name = "alfi-rms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "isort>=6.0.1",
    "pydantic>=2.10.6",
    "ruff>=0.9.7",
    "sqlalchemy>=2.0.38",
]
